name: Deploy React App to GitHub Pages

on:
  push:
    branches: ["master"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'  # Adjust if necessary

      - name: Install Dependencies
        run: npm install

      - name: Build React App
        run: npm run build

      - name: Prepare _site folder for deployment
        run: |
          mkdir _site
          cp -R build/* _site

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
        with:
          publish_dir: _site
